// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBcZ-EDcVOZ-O6he0Gmx8er4_YfltU_gqw',
    appId: '1:532581665819:web:89f392a59bbf8f6c31fcbe',
    messagingSenderId: '532581665819',
    projectId: 'krew-wash-faa79',
    authDomain: 'krew-wash-faa79.firebaseapp.com',
    storageBucket: 'krew-wash-faa79.firebasestorage.app',
    measurementId: 'G-62CV4HM1K2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKYMHoH7eNG2AcV2YMVHwB3ejQ8sxG3bw',
    appId: '1:1051906744816:android:9647be9110e19dafc77d35',
    messagingSenderId: '1051906744816',
    projectId: 'krew-carwash',
    storageBucket: 'krew-carwash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MTtGKD0gf8psPuuz908WFNIuBW0kZTQ',
    appId: '1:1051906744816:ios:50b910950ec05276c77d35',
    messagingSenderId: '1051906744816',
    projectId: 'krew-carwash',
    storageBucket: 'krew-carwash.firebasestorage.app',
    iosBundleId: 'com.decimaltechnology.krewwash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWpFZKPOxTfFW-Ru275hHa4c2SPFCyzZc',
    appId: '1:532581665819:ios:485a646cd82d0a4c31fcbe',
    messagingSenderId: '532581665819',
    projectId: 'krew-wash-faa79',
    storageBucket: 'krew-wash-faa79.firebasestorage.app',
    iosClientId: '532581665819-p56s1lh4mnf94lde8bk1b71ppno9ef6c.apps.googleusercontent.com',
    iosBundleId: 'com.decimaltechnology.krewwash',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBcZ-EDcVOZ-O6he0Gmx8er4_YfltU_gqw',
    appId: '1:532581665819:web:734eada7365b815231fcbe',
    messagingSenderId: '532581665819',
    projectId: 'krew-wash-faa79',
    authDomain: 'krew-wash-faa79.firebaseapp.com',
    storageBucket: 'krew-wash-faa79.firebasestorage.app',
    measurementId: 'G-C7TXZ3QLBM',
  );
}